### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by ayykamp** [antfu/FaceOnly#3]
Fails with the following error:
```
5:16:47 PM|Info|ErrorManager.AddError >> New error: FaceOnly 0.0.4 threw too many exceptions, disabled Plugin.
Make sure you are using the latest version of the Plugin and HDT.

System.MissingMethodException: Method not found: 'Int32 Hearthstone_Deck_Tracker.Hearthstone.Entities.Entity.GetTag(HearthDb.Enums.GameTag)'.
   at HDT.Plugins.FaceOnly.FaceOnly.OnUpdate()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Update() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 113
```

**Comment by antfu** [comment]
Thank you for the info.
I suppose this is due to the api changes of HDT. 
Would fix it when I got some time.

**Comment by ayykamp** [comment]
My bad, something was wrong with my hdt installation. Closing this
